#!/usr/bin/env python
"""Convert official PDF table candidates into a long finance fact candidate CSV."""

from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path


PROJECT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_OUT_DIR = PROJECT_DIR / "data" / "interim" / "official_budget_tables"

OUTPUT_FIELDS = [
    "institution_name",
    "year",
    "fiscal_stage",
    "document_type",
    "table_name",
    "metric_code",
    "metric_name",
    "amount_original",
    "unit_original",
    "amount_yi_yuan",
    "source_pdf",
    "source_url",
    "extraction_method",
    "verified",
    "notes",
]

METRIC_PATTERNS = [
    ("财政拨款收入", "fiscal_appropriation_income"),
    ("一般公共预算财政拨款", "general_public_budget_fiscal_appropriation"),
    ("事业收入", "undertaking_income"),
    ("其他收入", "other_income"),
    ("本年收入合计", "current_year_income_total"),
    ("本年收入", "current_year_income"),
    ("收入总计", "income_total"),
    ("使用非财政拨款结余", "non_fiscal_surplus_used"),
    ("上年结转", "carryover_from_previous_year"),
    ("本年支出合计", "current_year_expense_total"),
    ("支出总计", "expense_total"),
    ("教育支出", "education_expense"),
    ("科学技术支出", "science_technology_expense"),
    ("社会保障和就业支出", "social_security_employment_expense"),
    ("住房保障支出", "housing_security_expense"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Convert *_tables.csv to long finance fact candidates.")
    parser.add_argument("tables_csv", type=Path, help="CSV generated by official_pdf_extract.py")
    parser.add_argument("--out", type=Path, default=None, help="Output CSV path.")
    return parser.parse_args()


def clean_text(value: str | None) -> str:
    if value is None:
        return ""
    if value == "nan":
        return ""
    return re.sub(r"\s+", "", str(value)).strip()


def parse_amount(value: str) -> float | None:
    text = clean_text(value).replace(",", "")
    if not text:
        return None
    match = re.search(r"[-+]?\d+(?:\.\d+)?", text)
    if not match:
        return None
    return float(match.group())


def to_yi_yuan(amount: float, unit: str) -> float | None:
    if unit == "万元":
        return round(amount / 10000, 6)
    if unit == "亿元":
        return amount
    return None


def metric_code(metric_name: str) -> str:
    normalized = clean_text(metric_name)
    normalized = re.sub(r"^[一二三四五六七八九十]+、", "", normalized)
    for pattern, code in METRIC_PATTERNS:
        if pattern in normalized:
            return code
    return "unmapped"


def col_keys(row: dict[str, str]) -> list[str]:
    return sorted(k for k in row if re.fullmatch(r"col_\d{2}", k))


def iter_metric_pairs(row: dict[str, str]) -> list[tuple[str, str]]:
    keys = col_keys(row)
    pairs: list[tuple[str, str]] = []
    for idx in range(0, len(keys) - 1, 2):
        metric = clean_text(row.get(keys[idx]))
        amount = clean_text(row.get(keys[idx + 1]))
        if not metric or not amount:
            continue
        if parse_amount(amount) is None:
            continue
        pairs.append((metric, amount))
    return pairs


def convert(tables_csv: Path) -> list[dict[str, str]]:
    with tables_csv.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    out_rows: list[dict[str, str]] = []
    for row in rows:
        unit = clean_text(row.get("unit_hint")) or "万元"
        table_name = f"page_{row.get('page')}_table_{row.get('table_index')}"
        for metric_name, amount_original in iter_metric_pairs(row):
            amount = parse_amount(amount_original)
            if amount is None:
                continue
            amount_yi_yuan = to_yi_yuan(amount, unit)
            out_rows.append(
                {
                    "institution_name": row.get("university", ""),
                    "year": row.get("year", ""),
                    "fiscal_stage": "budget" if row.get("document_type") == "budget" else "",
                    "document_type": row.get("document_type", ""),
                    "table_name": table_name,
                    "metric_code": metric_code(metric_name),
                    "metric_name": metric_name,
                    "amount_original": amount_original,
                    "unit_original": unit,
                    "amount_yi_yuan": "" if amount_yi_yuan is None else f"{amount_yi_yuan:.6f}",
                    "source_pdf": row.get("source_pdf", ""),
                    "source_url": row.get("source_url", ""),
                    "extraction_method": "pymupdf_table_candidate",
                    "verified": "False",
                    "notes": "auto-converted from official PDF table candidate; requires table/metric review",
                }
            )
    return out_rows


def main() -> None:
    args = parse_args()
    tables_csv = args.tables_csv.resolve()
    out_path = args.out or (DEFAULT_OUT_DIR / f"{tables_csv.stem.removesuffix('_tables')}_facts.csv")
    out_path.parent.mkdir(parents=True, exist_ok=True)

    rows = convert(tables_csv)
    with out_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=OUTPUT_FIELDS)
        writer.writeheader()
        writer.writerows(rows)

    print(f"facts: {out_path} ({len(rows)} rows)")


if __name__ == "__main__":
    main()
